---
# tasks file for CytadelHosting.php-oracle-oci8 # install-oracle-instantclient

#- name: create oinstall group
#  group:
#    name: "{{ _oracle_client.group }}
#    gid: "{{ _oracle_client.group_id }}"
#    state: present

#- name: create oracle user
#  user:
#    name: "{{ _oracle_client.user }}"
#    uid: "{{ _oracle_client.user_id }}"
#    group: "{{ _oracle_client.group  }}"
#    state: present

- name: Create the /opt/oracle directory.
  file:
    path: "{{ oracle_client_base }}"
    state: directory
    mode: 0755
    #owner: "{{ _oracle_client.user }}"
    #group: "{{ _oracle_client.group }}"

- name: Download oracle instantclient packages
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.filename }}"
  with_items: "{{ instantclient_packages }}"

- name: Unzip oracle instantclient packages
  unarchive:
    src: "/tmp/{{ item.filename }}"
    remote_src: true
    dest: "{{ oracle_client_base }}"
  with_items: "{{ instantclient_packages }}"

- name: link instantclient to extracted directory
  file:
    src: "{{ oracle_client_base }}/instantclient_21_1"
    dest: "{{ oracle_client_base }}/instantclient"
    state: "link"


- name: Add instantclient to ldconfig
  copy:
    content: "{{ oracle_client_base }}/instantclient"
    dest: '/etc/ld.so.conf.d/oracle.conf'
  notify: run ldconfig

- name: Add LD_LIBRARY_PATH to /etc/environment.
  lineinfile:
    dest: '/etc/environment'
    regexp: '^LD_LIBRARY_PATH'
    line: "LD_LIBRARY_PATH=\"{{ oracle_client_base }}/instantclient\""
    state: present

- name: Add ORACLE_HOME to environment
  lineinfile:
    dest: '/etc/environment'
    regexp: '^ORACLE_HOME'
    line: "ORACLE_HOME={{ oracle_client_base }}"
    state: present

- name: Add /opt/oracle/instantclient to $PATH.
  lineinfile:
    dest: /etc/environment
    regexp: '^PATH="([^"]*)"$'
    line: "PATH=\"{{ oracle_client_base }}/instantclient:\\1\""
    backrefs: yes
    state: present
