---
# tasks file for CytadelHosting.php-oracle-oci8 # install-php-oci8.yml

- name: Install packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "php{{ php_version }}-dev"
    - build-essential

# Avoid WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
- name: update PECL channel
  command: 'pecl channel-update pecl.php.net'

# On some distributions like Debian Linux, /tmp has a sticky bit (drwxrwxrwt) which blocks "pecl install oci8" execution
- name: create PECL temp dir /tmp-pecl
  file:
    path: "/tmp-pecl"
    state: directory
    mode: 0777 

- name: change PECL temp dir
  command: pear config-set temp_dir /tmp-pecl


# if we're here, that's because either oci8 is not installed yet, or we want to force reinstall (in case of OIC version change for instance)
- name: Force pecl uninstall oci8.
  shell: "pecl uninstall {{ oci8_package_name | default ('oci8-2.2.0') }}"
  ignore_errors: true
  when: oci8_force_reinstall

# pecl makes an error if oci8 is already installed, but this shouldn't happen as
# - either OCI8 absence has been checked in main.yml
# - or it just got uninstalled above
- name: Install pecl oci8.
  shell: "echo \"instantclient,{{ oracle_client_base }}/instantclient\" | pecl install {{ oci8_package_name | default ('oci8-2.2.0') }}"
  # ignore_errors: true

- name: Create the PHP oci8 mod file.
  lineinfile:
    dest: /etc/php/{{ php_version }}/mods-available/oci8.ini
    regexp: 'extension=oci8.so'
    line: 'extension=oci8.so'
    state: present
    create: yes

- name: Enable the PHP oci8 mod.
  command: phpenmod oci8
  notify: restart php-fpm
